-- DDL Script for IPL Predictor Database

-- Drop tables in correct order
DROP TABLE IF EXISTS user_answers CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS predictions CASCADE;
DROP TABLE IF EXISTS quiz_answers CASCADE;
DROP TABLE IF EXISTS h2h_stats CASCADE;
DROP TABLE IF EXISTS venue_stats CASCADE;
DROP TABLE IF EXISTS matches CASCADE;
DROP TABLE IF EXISTS players CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
 DROP TABLE IF EXISTS users CASCADE;
 DROP TABLE IF EXISTS email_verification_tokens CASCADE;

 -- Create users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    unique_user_id VARCHAR(50) UNIQUE,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(100),
    points INT DEFAULT 0,
    rank INT DEFAULT 0,
    is_active BOOLEAN DEFAULT FALSE,
    email_verified BOOLEAN DEFAULT FALSE,
    role VARCHAR(20) DEFAULT 'USER',
    created_at BIGINT,
    updated_at BIGINT
);

-- Create email verification tokens table
CREATE TABLE email_verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at BIGINT NOT NULL,
    used BOOLEAN DEFAULT FALSE,
    created_at BIGINT NOT NULL
);

CREATE INDEX idx_email_verification_tokens_email ON email_verification_tokens(email);
CREATE INDEX idx_email_verification_tokens_expires ON email_verification_tokens(expires_at);

-- Create teams table
CREATE TABLE teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_name VARCHAR(100) UNIQUE NOT NULL,
    short_name VARCHAR(10) UNIQUE NOT NULL,
    home_city VARCHAR(50),
    stadium VARCHAR(100),
    logo_url VARCHAR(255),
    team_color VARCHAR(20),
    matches_played INT DEFAULT 0,
    matches_won INT DEFAULT 0,
    matches_lost INT DEFAULT 0,
    net_run_rate DOUBLE DEFAULT 0.0,
    points INT DEFAULT 0
);

-- Create matches table
CREATE TABLE matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    home_team_id BIGINT NOT NULL,
    away_team_id BIGINT NOT NULL,
    winner_team_id BIGINT,
    venue VARCHAR(100) NOT NULL,
    match_date BIGINT NOT NULL,
    match_number INT UNIQUE NOT NULL,
    match_status VARCHAR(20),
    match_type VARCHAR(20) NOT NULL,
    home_team_score INT,
    away_team_score INT,
    home_team_overs VARCHAR(10),
    away_team_overs VARCHAR(10),
    result VARCHAR(100),
    home_win_probability INT,
    away_win_probability INT,
    match_duration INT DEFAULT 240,
    FOREIGN KEY (home_team_id) REFERENCES teams(id),
    FOREIGN KEY (away_team_id) REFERENCES teams(id),
    FOREIGN KEY (winner_team_id) REFERENCES teams(id)
);

-- Create h2h_stats table
CREATE TABLE h2h_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team1_id BIGINT NOT NULL,
    team2_id BIGINT NOT NULL,
    total_matches INT,
    team1_wins INT,
    team2_wins INT,
    FOREIGN KEY (team1_id) REFERENCES teams(id),
    FOREIGN KEY (team2_id) REFERENCES teams(id),
    UNIQUE (team1_id, team2_id)
);

-- Create venue_stats table
CREATE TABLE venue_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stadium VARCHAR(100) UNIQUE NOT NULL,
    city VARCHAR(50),
    pitch_type VARCHAR(20),
    avg_score INT,
    chasing_win_pct INT,
    dew_factor VARCHAR(20),
    boundary_size VARCHAR(20)
);

-- Create players table
CREATE TABLE players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_name VARCHAR(100) NOT NULL,
    short_name VARCHAR(20) UNIQUE NOT NULL,
    team_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    batting_style VARCHAR(20),
    bowling_style VARCHAR(20),
    age INT,
    nationality VARCHAR(30),
    image_url VARCHAR(255),
    matches_played INT DEFAULT 0,
    runs INT DEFAULT 0,
    wickets INT DEFAULT 0,
    strike_rate DOUBLE DEFAULT 0.0,
    economy DOUBLE DEFAULT 0.0,
    FOREIGN KEY (team_id) REFERENCES teams(id)
);

-- Create predictions table
CREATE TABLE predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    match_id BIGINT NOT NULL,
    predicted_winner_id BIGINT,
    is_correct BOOLEAN DEFAULT FALSE,
    points_earned INT DEFAULT 0,
    created_at BIGINT,
    home_probability INT,
    away_probability INT,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (match_id) REFERENCES matches(id),
    FOREIGN KEY (predicted_winner_id) REFERENCES teams(id),
    UNIQUE (user_id, match_id)
);

-- Create questions table
CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    question_text VARCHAR(1000) NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255),
    option_d VARCHAR(255),
    correct_option VARCHAR(5) NOT NULL,
    points_value INT DEFAULT 10,
    is_active BOOLEAN DEFAULT TRUE,
    question_type VARCHAR(50) NOT NULL,
    created_at BIGINT,
    FOREIGN KEY (match_id) REFERENCES matches(id)
);

-- Create user_answers table
CREATE TABLE user_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    selected_option VARCHAR(5) NOT NULL,
    is_correct BOOLEAN DEFAULT FALSE,
    points_earned INT DEFAULT 0,
    answered_at BIGINT,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (question_id) REFERENCES questions(id),
    UNIQUE (user_id, question_id)
);

-- Create indexes
CREATE INDEX idx_matches_match_date ON matches(match_date);
CREATE INDEX idx_matches_match_status ON matches(match_status);
CREATE INDEX idx_predictions_user_id ON predictions(user_id);
CREATE INDEX idx_predictions_match_id ON predictions(match_id);
CREATE INDEX idx_users_points ON users(points DESC);
CREATE INDEX idx_teams_points ON teams(points DESC);
CREATE INDEX idx_questions_match_id ON questions(match_id);
CREATE INDEX idx_user_answers_user_id ON user_answers(user_id);
CREATE INDEX idx_user_answers_question_id ON user_answers(question_id);

-- Create quiz_answers table for match-specific quiz predictions
DROP TABLE IF EXISTS quiz_answers;
CREATE TABLE quiz_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    match_id BIGINT NOT NULL,
    question_id VARCHAR(50) NOT NULL,
    selected_option VARCHAR(255) NOT NULL,
    is_correct BOOLEAN DEFAULT FALSE,
    points_earned INT DEFAULT 0,
    created_at BIGINT,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (match_id) REFERENCES matches(id),
    UNIQUE (user_id, match_id, question_id)
);

CREATE INDEX idx_quiz_answers_user_id ON quiz_answers(user_id);
CREATE INDEX idx_quiz_answers_match_id ON quiz_answers(match_id);
